### ISSUE TITLE
Reorder Tabs within Group

### ISSUE THREAD

**Issue by bobcat2085** [bentodaniel/vs-tab-groups#2]
It would be great to be able to reorder tabs within a specific tab group.

As it is now, you must open a tab group, remove the tab group, reorder your open tabs, then recreate the tab group.

**Comment by GSoftwareDevelopment** [comment]
I join in this request

**Comment by bentodaniel** [comment]
i'm not quite sure if i could implement this with a drag and drop, which would be way more convenient, however i've implemented it as a clickable action, because i do agree it would be a nice to have

**Comment by GSoftwareDevelopment** [comment]
Most importantly there is the ability to move the pieces around - great job.

**Comment by GSoftwareDevelopment** [comment]
I actually had this idea, but it's just an idea :)
The stacking of tabs in a group could be done based on the order of the tabs in the editor. The update button, would stack the tabs according to the order. Of course, the update would only take place for the tabs defined in the group.

But as I say, this is just an idea. It's great to be able to arrange the content anyway :)

BTW: I'm pleasantly surprised, by the quick introduction of this functionality, as it's in my opinion, the most fitting add-on for what I need at the moment and I'll probably use it in many other projects too.

**Comment by bentodaniel** [comment]
that's also pretty doable, i'll work on an update button, to set the order of a group as its tabs are in the editor. Tabs from a group that are not open will be set to last place and their relative order left unchanged

**Comment by bentodaniel** [comment]
Added the feature as an option in the "More Actions.." button (the elipsis in top right of the editor)
