### ISSUE TITLE
Plugin visibility problem.

### ISSUE THREAD

**Issue by GSoftwareDevelopment** [bentodaniel/vs-tab-groups#7]
By right-clicking so as to bring up a list of available tabs, the `VS TAB GROUP` plugin does not appear in this list - there is a blank space. Example below:

![image](https://github.com/bentodaniel/vs-tab-groups/assets/67878622/72811bed-3e14-4e7d-8ebe-b630bc477361)

**Comment by bentodaniel** [comment]
Should be fixed, as soon as I update the extension version. Thank you

**Comment by GSoftwareDevelopment** [comment]
Now it's visible - great
